=== skyritsis/VehicleManagement/build/classes/vehiclemanagement/VehicleManagement.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/VehicleManagement"
    xmlns:tns="http://xml.netbeans.org/schema/VehicleManagement"
    elementFormDefault="qualified">
    <xsd:element name="Vehicle">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="CompaniesAssociated">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Manufacturer" type="xsd:Name"/>
                            <xsd:element name="CoManufacturer" type="xsd:Name"/>
                            <xsd:element name="CopyrightAgreement" type="xsd:anyURI"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="VehicleDetails">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ModelName" type="xsd:Name"/>
                            <xsd:element name="CreationDate" type="xsd:date"/>
                            <xsd:element name="VehicleType" type="xsd:string"/>
                            <xsd:element name="VehicleIdentificationNumber" type="xsd:string"/>
                            <xsd:element name="VehicleAncestor" type="xsd:NCName"/>
                            <xsd:element name="VehicleDescendant" type="xsd:NCName"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="DistributionDetails">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Distributor" type="xsd:Name"/>
                            <xsd:element name="DistributionManualLanguage" type="xsd:string"/>
                            <xsd:element name="DistributorWarranty">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="WarrantyStart" type="xsd:date"/>
                                        <xsd:element name="WarrantyEnd" type="xsd:date"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== skyritsis/VehicleManagement/src/vehiclemanagement/VehicleManagement.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : VehicleManagement.xml
    Created on : January 15, 2012, 6:16 PM
    Author     : Sarantis
    Description:
        Purpose of the document follows.
-->

<ns0:Vehicle  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
              xmlns:ns0='http://xml.netbeans.org/schema/VehicleManagement'
              xsi:schemaLocation='http://xml.netbeans.org/schema/VehicleManagement VehicleManagement.xsd'>
    <ns0:CompaniesAssociated>
        <ns0:Manufacturer></ns0:Manufacturer>
        <ns0:CoManufacturer></ns0:CoManufacturer>
        <ns0:CopyrightAgreement></ns0:CopyrightAgreement>
    </ns0:CompaniesAssociated>
    <ns0:VehicleDetails>
        <ns0:ModelName></ns0:ModelName>
        <ns0:CreationDate></ns0:CreationDate>
        <ns0:VehicleType></ns0:VehicleType>
        <ns0:VehicleIdentificationNumber></ns0:VehicleIdentificationNumber>
        <ns0:VehicleAncestor></ns0:VehicleAncestor>
        <ns0:VehicleDescendant></ns0:VehicleDescendant>
    </ns0:VehicleDetails>
    <ns0:DistributionDetails>
        <ns0:Distributor></ns0:Distributor>
        <ns0:DistributionManualLanguage></ns0:DistributionManualLanguage>
        <ns0:DistributorWarranty>
            <ns0:WarrantyStart></ns0:WarrantyStart>
            <ns0:WarrantyEnd></ns0:WarrantyEnd>
        </ns0:DistributorWarranty>
    </ns0:DistributionDetails>

</ns0:Vehicle>
